export const GET_HOTELS_REQUEST="GET_HOTEL_REQUEST"
export const GET_HOTELS_SUCCESS="GET_HOTEL_SUCCESS"
export const GET_HOTELS_ERROR="GET_HOTEL_ERROR"

export const SET_CONTENT_DATA = 'SET_CONTENT_DATA';
export const SET_ROOM_DATA = 'SET_ROOM_DATA';
export const SET_FAQ_DATA = 'SET_FAQ_DATA';
export const SET_ATTRIBUTES_DATA = 'SET_ATTRIBUTES_DATA';

export const SET_COMBINED_DATA_SUCCESS = 'SET_COMBINED_DATA_SUCCESS';
export const SET_COMBINED_DATA_ERROR = 'SET_COMBINED_DATA_ERROR';
